#!/usr/bin/env python3
import os
import argparse
from datetime import datetime

# =============================================================================
# Configuration: Project Structure & Exclusion Rules
# =============================================================================

# Files/Directories to always exclude (even if they match include patterns)
EXCLUDE_DIRS = {
    ".git", "__pycache__", "build", "dist", "node_modules",
    ".idea", ".vscode", "cmake-build-debug", "cmake-build-release",
    "bin", "obj", "lib", ".build_tmp"
}

EXCLUDE_FILES = {
    ".DS_Store", "Thumbs.db", "package-lock.json", "yarn.lock"
}

# File extensions to include in the export
INCLUDE_EXTENSIONS = {
    # C/C++
    ".cpp", ".hpp", ".c", ".h", ".cc", ".hh", ".cxx", ".hxx",
    # Qt/QML
    ".qml", ".qrc", ".ui", ".pro", ".pri",
    # Build Systems
    ".cmake", "CMakeLists.txt", "Makefile",
    # Scripts
    ".sh", ".bash", ".py", ".lua",
    # Config/Data
    ".json", ".xml", ".yaml", ".yml", ".toml", ".ini", ".conf",
    # Documentation
    ".md", ".txt", ".rst"
}

# Specific filenames to always include (regardless of extension)
INCLUDE_FILENAMES = {
    "CMakeLists.txt", "Dockerfile", "Vagrantfile", ".gitignore", "LICENSE", "README"
}

def is_text_file(filepath):
    """
    Heuristic to check if a file is text (vs binary).
    Reads the first 1024 bytes and checks for null bytes.
    """
    try:
        with open(filepath, 'rb') as f:
            chunk = f.read(1024)
            if b'\x00' in chunk:
                return False
            return True
    except Exception:
        return False

def should_process(filepath):
    """
    Determines if a file should be included in the export.
    """
    filename = os.path.basename(filepath)
    ext = os.path.splitext(filename)[1].lower()

    if filename in EXCLUDE_FILES:
        return False
    
    if filename in INCLUDE_FILENAMES:
        return True
    
    if ext in INCLUDE_EXTENSIONS:
        return True
    
    # If no extension match, basic text check (optional, can be strict)
    # return is_text_file(filepath) 
    return False

def generate_export(output_file="project_context.txt", root_dir="."):
    """
    Traverses the directory and writes content to the output file.
    """
    abs_root = os.path.abspath(root_dir)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        with open(output_file, 'w', encoding='utf-8') as out:
            # --- Header ---
            out.write(f"# Project Export\n")
            out.write(f"# Root: {abs_root}\n")
            out.write(f"# Date: {timestamp}\n")
            out.write(f"# Generated by: export.py\n")
            out.write("="*80 + "\n\n")

            # --- File Tree ---
            out.write("## File Tree ##\n")
            for root, dirs, files in os.walk(abs_root):
                # Modify dirs in-place to skip excluded directories
                dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
                
                level = root.replace(abs_root, '').count(os.sep)
                indent = ' ' * 4 * (level)
                out.write(f"{indent}{os.path.basename(root)}/\n")
                subindent = ' ' * 4 * (level + 1)
                for f in sorted(files):
                    if should_process(os.path.join(root, f)):
                        out.write(f"{subindent}{f}\n")
            out.write("\n" + "="*80 + "\n\n")

            # --- File Contents ---
            for root, dirs, files in os.walk(abs_root):
                dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS] # Skip dirs

                for filename in sorted(files):
                    filepath = os.path.join(root, filename)
                    
                    # Skip the output file itself to avoid infinite loop
                    if os.path.abspath(filepath) == os.path.abspath(output_file):
                        continue
                    
                    if os.path.basename(filepath) == "export.py":
                        continue

                    if should_process(filepath):
                        rel_path = os.path.relpath(filepath, abs_root)
                        
                        out.write(f"FILE: {rel_path}\n")
                        out.write("-" * 80 + "\n")
                        
                        try:
                            with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                                content = f.read()
                                out.write(content)
                                if not content.endswith('\n'):
                                    out.write('\n')
                        except Exception as e:
                            out.write(f"[Error reading file: {e}]\n")
                        
                        out.write("-" * 80 + "\n\n")
            
            print(f"✅ Export completed: {output_file}")

    except IOError as e:
        print(f"❌ Error writing output file: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export project source code to a single text file.")
    parser.add_argument("-o", "--output", default="project_context.txt", help="Output filename")
    parser.add_argument("-d", "--dir", default=".", help="Root directory to scan")
    
    args = parser.parse_args()
    generate_export(args.output, args.dir)
